server:
  port: 8099

spring:
  datasource:
    admin:
      url: jdbc:mysql://10.10.2.100:3306/i61-draw-course-admin?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
      driver: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false